/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PantheonRouteImport } from './routes/pantheon'
import { Route as LoreRouteImport } from './routes/lore'
import { Route as ChoirRouteImport } from './routes/choir'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AetherRouteImport } from './routes/aether'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSanctumRouteImport } from './routes/_authenticated/sanctum'
import { Route as AuthenticatedSanctumInvokeRouteImport } from './routes/_authenticated/sanctum.invoke'

const PantheonRoute = PantheonRouteImport.update({
  id: '/pantheon',
  path: '/pantheon',
  getParentRoute: () => rootRouteImport,
} as any)
const LoreRoute = LoreRouteImport.update({
  id: '/lore',
  path: '/lore',
  getParentRoute: () => rootRouteImport,
} as any)
const ChoirRoute = ChoirRouteImport.update({
  id: '/choir',
  path: '/choir',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AetherRoute = AetherRouteImport.update({
  id: '/aether',
  path: '/aether',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSanctumRoute = AuthenticatedSanctumRouteImport.update({
  id: '/sanctum',
  path: '/sanctum',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSanctumInvokeRoute =
  AuthenticatedSanctumInvokeRouteImport.update({
    id: '/invoke',
    path: '/invoke',
    getParentRoute: () => AuthenticatedSanctumRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aether': typeof AetherRoute
  '/auth': typeof AuthRoute
  '/choir': typeof ChoirRoute
  '/lore': typeof LoreRoute
  '/pantheon': typeof PantheonRoute
  '/sanctum': typeof AuthenticatedSanctumRouteWithChildren
  '/sanctum/invoke': typeof AuthenticatedSanctumInvokeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aether': typeof AetherRoute
  '/auth': typeof AuthRoute
  '/choir': typeof ChoirRoute
  '/lore': typeof LoreRoute
  '/pantheon': typeof PantheonRoute
  '/sanctum': typeof AuthenticatedSanctumRouteWithChildren
  '/sanctum/invoke': typeof AuthenticatedSanctumInvokeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/aether': typeof AetherRoute
  '/auth': typeof AuthRoute
  '/choir': typeof ChoirRoute
  '/lore': typeof LoreRoute
  '/pantheon': typeof PantheonRoute
  '/_authenticated/sanctum': typeof AuthenticatedSanctumRouteWithChildren
  '/_authenticated/sanctum/invoke': typeof AuthenticatedSanctumInvokeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aether'
    | '/auth'
    | '/choir'
    | '/lore'
    | '/pantheon'
    | '/sanctum'
    | '/sanctum/invoke'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aether'
    | '/auth'
    | '/choir'
    | '/lore'
    | '/pantheon'
    | '/sanctum'
    | '/sanctum/invoke'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/aether'
    | '/auth'
    | '/choir'
    | '/lore'
    | '/pantheon'
    | '/_authenticated/sanctum'
    | '/_authenticated/sanctum/invoke'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AetherRoute: typeof AetherRoute
  AuthRoute: typeof AuthRoute
  ChoirRoute: typeof ChoirRoute
  LoreRoute: typeof LoreRoute
  PantheonRoute: typeof PantheonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pantheon': {
      id: '/pantheon'
      path: '/pantheon'
      fullPath: '/pantheon'
      preLoaderRoute: typeof PantheonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lore': {
      id: '/lore'
      path: '/lore'
      fullPath: '/lore'
      preLoaderRoute: typeof LoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/choir': {
      id: '/choir'
      path: '/choir'
      fullPath: '/choir'
      preLoaderRoute: typeof ChoirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aether': {
      id: '/aether'
      path: '/aether'
      fullPath: '/aether'
      preLoaderRoute: typeof AetherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sanctum': {
      id: '/_authenticated/sanctum'
      path: '/sanctum'
      fullPath: '/sanctum'
      preLoaderRoute: typeof AuthenticatedSanctumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sanctum/invoke': {
      id: '/_authenticated/sanctum/invoke'
      path: '/invoke'
      fullPath: '/sanctum/invoke'
      preLoaderRoute: typeof AuthenticatedSanctumInvokeRouteImport
      parentRoute: typeof AuthenticatedSanctumRoute
    }
  }
}

interface AuthenticatedSanctumRouteChildren {
  AuthenticatedSanctumInvokeRoute: typeof AuthenticatedSanctumInvokeRoute
}

const AuthenticatedSanctumRouteChildren: AuthenticatedSanctumRouteChildren = {
  AuthenticatedSanctumInvokeRoute: AuthenticatedSanctumInvokeRoute,
}

const AuthenticatedSanctumRouteWithChildren =
  AuthenticatedSanctumRoute._addFileChildren(AuthenticatedSanctumRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSanctumRoute: typeof AuthenticatedSanctumRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSanctumRoute: AuthenticatedSanctumRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AetherRoute: AetherRoute,
  AuthRoute: AuthRoute,
  ChoirRoute: ChoirRoute,
  LoreRoute: LoreRoute,
  PantheonRoute: PantheonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
