/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SanctumRouteImport } from './routes/sanctum'
import { Route as PantheonRouteImport } from './routes/pantheon'
import { Route as IndexRouteImport } from './routes/index'

const SanctumRoute = SanctumRouteImport.update({
  id: '/sanctum',
  path: '/sanctum',
  getParentRoute: () => rootRouteImport,
} as any)
const PantheonRoute = PantheonRouteImport.update({
  id: '/pantheon',
  path: '/pantheon',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pantheon': typeof PantheonRoute
  '/sanctum': typeof SanctumRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pantheon': typeof PantheonRoute
  '/sanctum': typeof SanctumRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pantheon': typeof PantheonRoute
  '/sanctum': typeof SanctumRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pantheon' | '/sanctum'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pantheon' | '/sanctum'
  id: '__root__' | '/' | '/pantheon' | '/sanctum'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PantheonRoute: typeof PantheonRoute
  SanctumRoute: typeof SanctumRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sanctum': {
      id: '/sanctum'
      path: '/sanctum'
      fullPath: '/sanctum'
      preLoaderRoute: typeof SanctumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pantheon': {
      id: '/pantheon'
      path: '/pantheon'
      fullPath: '/pantheon'
      preLoaderRoute: typeof PantheonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PantheonRoute: PantheonRoute,
  SanctumRoute: SanctumRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
