/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SanctumRouteImport } from './routes/sanctum'
import { Route as PantheonRouteImport } from './routes/pantheon'
import { Route as LoreRouteImport } from './routes/lore'
import { Route as ChoirRouteImport } from './routes/choir'
import { Route as AetherRouteImport } from './routes/aether'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SanctumInvokeRouteImport } from './routes/sanctum.invoke'

const SanctumRoute = SanctumRouteImport.update({
  id: '/sanctum',
  path: '/sanctum',
  getParentRoute: () => rootRouteImport,
} as any)
const PantheonRoute = PantheonRouteImport.update({
  id: '/pantheon',
  path: '/pantheon',
  getParentRoute: () => rootRouteImport,
} as any)
const LoreRoute = LoreRouteImport.update({
  id: '/lore',
  path: '/lore',
  getParentRoute: () => rootRouteImport,
} as any)
const ChoirRoute = ChoirRouteImport.update({
  id: '/choir',
  path: '/choir',
  getParentRoute: () => rootRouteImport,
} as any)
const AetherRoute = AetherRouteImport.update({
  id: '/aether',
  path: '/aether',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SanctumInvokeRoute = SanctumInvokeRouteImport.update({
  id: '/invoke',
  path: '/invoke',
  getParentRoute: () => SanctumRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aether': typeof AetherRoute
  '/choir': typeof ChoirRoute
  '/lore': typeof LoreRoute
  '/pantheon': typeof PantheonRoute
  '/sanctum': typeof SanctumRouteWithChildren
  '/sanctum/invoke': typeof SanctumInvokeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aether': typeof AetherRoute
  '/choir': typeof ChoirRoute
  '/lore': typeof LoreRoute
  '/pantheon': typeof PantheonRoute
  '/sanctum': typeof SanctumRouteWithChildren
  '/sanctum/invoke': typeof SanctumInvokeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aether': typeof AetherRoute
  '/choir': typeof ChoirRoute
  '/lore': typeof LoreRoute
  '/pantheon': typeof PantheonRoute
  '/sanctum': typeof SanctumRouteWithChildren
  '/sanctum/invoke': typeof SanctumInvokeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aether'
    | '/choir'
    | '/lore'
    | '/pantheon'
    | '/sanctum'
    | '/sanctum/invoke'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aether'
    | '/choir'
    | '/lore'
    | '/pantheon'
    | '/sanctum'
    | '/sanctum/invoke'
  id:
    | '__root__'
    | '/'
    | '/aether'
    | '/choir'
    | '/lore'
    | '/pantheon'
    | '/sanctum'
    | '/sanctum/invoke'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AetherRoute: typeof AetherRoute
  ChoirRoute: typeof ChoirRoute
  LoreRoute: typeof LoreRoute
  PantheonRoute: typeof PantheonRoute
  SanctumRoute: typeof SanctumRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sanctum': {
      id: '/sanctum'
      path: '/sanctum'
      fullPath: '/sanctum'
      preLoaderRoute: typeof SanctumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pantheon': {
      id: '/pantheon'
      path: '/pantheon'
      fullPath: '/pantheon'
      preLoaderRoute: typeof PantheonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lore': {
      id: '/lore'
      path: '/lore'
      fullPath: '/lore'
      preLoaderRoute: typeof LoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/choir': {
      id: '/choir'
      path: '/choir'
      fullPath: '/choir'
      preLoaderRoute: typeof ChoirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aether': {
      id: '/aether'
      path: '/aether'
      fullPath: '/aether'
      preLoaderRoute: typeof AetherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sanctum/invoke': {
      id: '/sanctum/invoke'
      path: '/invoke'
      fullPath: '/sanctum/invoke'
      preLoaderRoute: typeof SanctumInvokeRouteImport
      parentRoute: typeof SanctumRoute
    }
  }
}

interface SanctumRouteChildren {
  SanctumInvokeRoute: typeof SanctumInvokeRoute
}

const SanctumRouteChildren: SanctumRouteChildren = {
  SanctumInvokeRoute: SanctumInvokeRoute,
}

const SanctumRouteWithChildren =
  SanctumRoute._addFileChildren(SanctumRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AetherRoute: AetherRoute,
  ChoirRoute: ChoirRoute,
  LoreRoute: LoreRoute,
  PantheonRoute: PantheonRoute,
  SanctumRoute: SanctumRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
